service: matf-ev-charger-app

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: local
  environment:
    OCM_API_KEY: '69d86e58-df21-406b-b837-cc07c35ddd41'
    OCM_URL: 'https://api.openchargemap.io/v3/poi'
    DYNAMODB_TABLE: matf-ev-charger-app-chargers-local

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: false

functions:
  GetChargers:
    handler: backend/handlers/charger_handler.get_all
    events:
      - http:
          path: chargers
          method: get
          cors: true

  SyncOCM:
    handler: backend/handlers/sync_handler.sync_data
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: sync
          method: get
      - schedule:
          rate: rate(1 minute)

  UpdateStatus:
    handler: backend/handlers/charger_handler.update_status
    events:
      - http:
          path: chargers/status
          method: post
          cors: true

resources:
  - ${file(infra/resources.yml)}
